version: "3.9"


services:
  mongo:
    image: mongo:6.0
    container_name: medical-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./init-mongo/init-users.js:/docker-entrypoint-initdb.d/init-users.js:ro
    networks:
      - medical-net


  migration:
    build: .
    container_name: medical-migration
    depends_on:
      - mongo
    env_file:
      - .env
    command: sh -c "python src/migrate.py && python src/create_indexes.py"
    networks:
      - medical-net


volumes:
  mongo_data:


networks:
  medical-net:
    driver: bridge